### ISSUE TITLE
Can't return the persistentId when we do PFOP

### ISSUE THREAD

**Issue by licic1995** [die-welle/tiny-qiniu#3]
When we do [PFOP](https://developer.qiniu.com/dora/manual/3686/pfop-directions-for-use#1) automatically after uploading, it always return a `persistentId` to query PFOP status.
But when calling `responseURL`, it just return `data.hash` and `data.key`.
How about adding `data.persistentId` in it?

**Comment by Cap32** [comment]
[v0.5.0](https://github.com/die-welle/tiny-qiniu/releases/tag/v0.5.0) added `mapResponse` option.

Example:

```js
const config = {
  mapResponse(data) { return data.persistentId; },
  // ...
};
const tinyQiniu = new TinyQiniu(config);
const persistetId = await tinyQiniu.uploadFile(file);
```
